/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import context.IAuthContext;
import controllers.OrdersController;
import controllers.ProductsController;
import controllers.UsersController;
import entities.User;
import enums.Controller;
import enums.CrudFunctionality;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import utils.ICallback;

/**
 *
 * @author Paulo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form JPedidosForm
     */
    
    private IAuthContext _authContext;
    private OrdersController _ordersController;
    private UsersController _usersController;
    private ProductsController _productsController;
    
    public MainForm(
        IAuthContext authContext,
        OrdersController ordersController,
        UsersController usersController,
        ProductsController productsController
    ) {
        initComponents();
        
        _authContext = authContext;
        _ordersController = ordersController;
        _usersController = usersController;
        _productsController = productsController;
        updateTitle();
        toggleMenus();
        setBG();
    }
    
    private void setBG() {
      this.getContentPane().setBackground(Color.GRAY);
    }
    
    private void updateTitle() {
        User currentUser = _ordersController.getCurrentUser();
        setTitle("JPedidos - (" + currentUser.getRoleString() + ")" + " - Usuário: " +  currentUser.getName() + " - Email: " + currentUser.getEmail());
    }
    
    private void toggleMenus() {
        mi_users.setVisible(_authContext.hasPermission(Controller.Users, CrudFunctionality.Create));
        mi_products.setVisible(_authContext.hasPermission(Controller.Products, CrudFunctionality.Create));
        mi_customers.setVisible(_authContext.hasPermission(Controller.Customers, CrudFunctionality.Create));
        mi_orders.setVisible(_authContext.hasPermission(Controller.Orders, CrudFunctionality.List));
        mi_new_order.setVisible(_authContext.hasPermission(Controller.Orders, CrudFunctionality.Create));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_users = new javax.swing.JMenuItem();
        mi_products = new javax.swing.JMenuItem();
        mi_customers = new javax.swing.JMenuItem();
        mi_orders = new javax.swing.JMenuItem();
        mi_new_order = new javax.swing.JMenuItem();
        mi_change_pass = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_logout = new javax.swing.JMenuItem();
        mi_close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setForeground(java.awt.Color.red);

        jLabel1.setText("jLabel1");

        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mi_users.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_users.setText("Usuários");
        mi_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_usersActionPerformed(evt);
            }
        });
        jMenu1.add(mi_users);

        mi_products.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_products.setText("Produtos");
        mi_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_productsActionPerformed(evt);
            }
        });
        jMenu1.add(mi_products);

        mi_customers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_customers.setText("Clientes");
        jMenu1.add(mi_customers);

        mi_orders.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_orders.setText("Pedidos");
        mi_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ordersActionPerformed(evt);
            }
        });
        jMenu1.add(mi_orders);

        mi_new_order.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_new_order.setText("Lançar Pedido");
        mi_new_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_new_orderActionPerformed(evt);
            }
        });
        jMenu1.add(mi_new_order);

        mi_change_pass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_change_pass.setText("Trocar senha");
        mi_change_pass.setActionCommand("Trocar senha");
        mi_change_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_change_passActionPerformed(evt);
            }
        });
        jMenu1.add(mi_change_pass);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mi_logout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_logout.setText("Sair");
        mi_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_logoutActionPerformed(evt);
            }
        });
        jMenu2.add(mi_logout);

        mi_close.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mi_close.setText("Fechar");
        mi_close.setName(""); // NOI18N
        mi_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_closeActionPerformed(evt);
            }
        });
        jMenu2.add(mi_close);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mi_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ordersActionPerformed
        new OrderList(_ordersController).setVisible(true);
    }//GEN-LAST:event_mi_ordersActionPerformed

    private void mi_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_logoutActionPerformed
        _usersController.logout();
        new LoginForm(
            _authContext,
            _usersController, 
            _ordersController, 
            _productsController
        ).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mi_logoutActionPerformed

    private void mi_new_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_new_orderActionPerformed
        new OrderForm(_ordersController).setVisible(true);
    }//GEN-LAST:event_mi_new_orderActionPerformed

    private void mi_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_usersActionPerformed
        new UserForm(_usersController).setVisible(true);
    }//GEN-LAST:event_mi_usersActionPerformed

    private void mi_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mi_closeActionPerformed

    private void mi_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_productsActionPerformed
        new ProductForm(_productsController).setVisible(true);
    }//GEN-LAST:event_mi_productsActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mi_change_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_change_passActionPerformed
            ICallback callback = new ICallback() {
            @Override
            public void run() {
                System.out.println("Changing password");
            }
        };
        new ChangePasswordForm(_usersController, callback).setVisible(true);
    }//GEN-LAST:event_mi_change_passActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mi_change_pass;
    private javax.swing.JMenuItem mi_close;
    private javax.swing.JMenuItem mi_customers;
    private javax.swing.JMenuItem mi_logout;
    private javax.swing.JMenuItem mi_new_order;
    private javax.swing.JMenuItem mi_orders;
    private javax.swing.JMenuItem mi_products;
    private javax.swing.JMenuItem mi_users;
    // End of variables declaration//GEN-END:variables
}
